name: Deploy Google Cloud Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps function1
        working-directory: ./Function-1
        run: npm install

      - name: Install deps function2
        working-directory: ./Function-2
        run: npm install

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_FUNCTIONS_PROJECT_ID }}

      - name: Deploy function1 (Gen2)
        env:
          REGION: ${{ secrets.GOOGLE_FUNCTIONS_REGION }}
          PROJECT: ${{ secrets.GOOGLE_FUNCTIONS_PROJECT_ID }}
        run: |
          gcloud functions deploy callstartapis-v1 \
            --gen2 \
            --runtime nodejs20 \
            --region "$REGION" \
            --project "$PROJECT" \
            --trigger-http \
            --allow-unauthenticated \
            --entry-point helloHttp \
            --source ./Function-1

      - name: Deploy function2 (Gen2)
        env:
          REGION: ${{ secrets.GOOGLE_FUNCTIONS_REGION }}
          PROJECT: ${{ secrets.GOOGLE_FUNCTIONS_PROJECT_ID }}
        run: |
          gcloud functions deploy callstartapis-v2 \
            --gen2 \
            --runtime nodejs20 \
            --region "$REGION" \
            --project "$PROJECT" \
            --trigger-http \
            --allow-unauthenticated \
            --entry-point helloHttp \
            --source ./Function-2
