name: Deploy Cloud Functions with Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repo
        uses: actions/checkout@v4

      # Auth to GCP
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Init Terraform
      - name: Terraform Init
        run: terraform init

      # Plan
      - name: Terraform Plan
        run: terraform plan -var="project_id=${{ secrets.GOOGLE_FUNCTIONS_PROJECT_ID }}" \
                            -var="region=${{ secrets.GOOGLE_FUNCTIONS_REGION }}" \
                            -var='functions=${{ secrets.FUNCTIONS_LIST }}'

      # Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="project_id=${{ secrets.GOOGLE_FUNCTIONS_PROJECT_ID }}" \
                             -var="region=${{ secrets.GOOGLE_FUNCTIONS_REGION }}" \
                             -var='functions=${{ secrets.FUNCTIONS_LIST }}'
