name: Deploy Cloud Functions with Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Authenticate to GCP
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4️⃣ Convert FUNCTIONS_LIST secret to Terraform list
      - name: Prepare Terraform variables
        run: |
          FUNCTIONS_LIST=$(echo "${{ secrets.FUNCTIONS_LIST }}" | tr ',' '\n' | awk '{printf "\"%s\",",$0}' | sed 's/,$//')
          echo "FUNCTIONS_LIST=[$FUNCTIONS_LIST]" >> $GITHUB_ENV

      # 5️⃣ Terraform Init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # 6️⃣ Terraform Plan
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan \
              -var="project_id=${{ secrets.GOOGLE_FUNCTIONS_PROJECT_ID }}" \
              -var="region=${{ secrets.GOOGLE_FUNCTIONS_REGION }}" \
              -var="functions=${FUNCTIONS_LIST}"

      # 7️⃣ Terraform Apply
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve \
              -var="project_id=${{ secrets.GOOGLE_FUNCTIONS_PROJECT_ID }}" \
              -var="region=${{ secrets.GOOGLE_FUNCTIONS_REGION }}" \
              -var="functions=${FUNCTIONS_LIST}"
