name: Deploy Google Cloud Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_FUNCTIONS_PROJECT_ID }}

      - name: Run deploy batch
        env:
          REGION: ${{ secrets.GOOGLE_FUNCTIONS_REGION }}
          PROJECT: ${{ secrets.GOOGLE_FUNCTIONS_PROJECT_ID }}
          FUNCTIONS: ${{ secrets.GOOGLE_FUNCTIONS_LIST }}
        run: |
          ./Deploy_Fucntions.bat
